pre-release-commit-message = "release {{version}}"

pre-release-replacements = [
    { file = "solv/Cargo.toml", search = "path = \"\.\./solp/\", version = \"[a-z0-9\\.-]+\"", replace = "path = \"../solp/\", version = \"{{version}}\"" },
]