pre-release-commit-message = "release {{version}}"
no-dev-version = true
tag-prefix = "v"

post-release-replacements = [
    { file = "Cargo.toml", search = "path = \"\\.\\./solp/\", version = \"[a-z0-9\\.-]+\"", replace = "path = \"../solp/\", version = \"{{version}}\"" },
]